create table "public"."consigne" (
    "id" bigint generated by default as identity not null,
    "date" date not null,
    "point_de_collecte_id" bigint,
    "consigne" bigint not null,
    "deconsigne" bigint not null,
    "montant" double precision not null
);

alter table
    "public"."consigne" enable row level security;

alter table
    "public"."point_de_collecte"
add
    column "consigne" boolean not null default true;

CREATE UNIQUE INDEX consigne_pkey ON public.consigne USING btree (id);

alter table
    "public"."consigne"
add
    constraint "consigne_pkey" PRIMARY KEY using index "consigne_pkey";

alter table
    "public"."consigne"
add
    constraint "consigne_point_de_collecte_id_fkey" FOREIGN KEY (point_de_collecte_id) REFERENCES point_de_collecte(id) ON UPDATE CASCADE ON DELETE
SET
    NULL not valid;

alter table
    "public"."consigne" validate constraint "consigne_point_de_collecte_id_fkey";

grant delete on table "public"."consigne" to "anon";

grant
insert
    on table "public"."consigne" to "anon";

grant references on table "public"."consigne" to "anon";

grant
select
    on table "public"."consigne" to "anon";

grant trigger on table "public"."consigne" to "anon";

grant truncate on table "public"."consigne" to "anon";

grant
update
    on table "public"."consigne" to "anon";

grant delete on table "public"."consigne" to "authenticated";

grant
insert
    on table "public"."consigne" to "authenticated";

grant references on table "public"."consigne" to "authenticated";

grant
select
    on table "public"."consigne" to "authenticated";

grant trigger on table "public"."consigne" to "authenticated";

grant truncate on table "public"."consigne" to "authenticated";

grant
update
    on table "public"."consigne" to "authenticated";

grant delete on table "public"."consigne" to "service_role";

grant
insert
    on table "public"."consigne" to "service_role";

grant references on table "public"."consigne" to "service_role";

grant
select
    on table "public"."consigne" to "service_role";

grant trigger on table "public"."consigne" to "service_role";

grant truncate on table "public"."consigne" to "service_role";

grant
update
    on table "public"."consigne" to "service_role";

create policy "Allow create for everyone" on "public"."consigne" as permissive for
insert
    to anon,
    authenticated with check (true);

create policy "Allow select for everyone" on "public"."consigne" as permissive for
select
    to anon,
    authenticated using (true);